pub mod config;
#[cfg(feature = "ec2")]
pub mod ec2;
#[cfg(feature = "s3")]
pub mod s3;
#[cfg(feature = "lambda")]
pub mod lambda;
#[cfg(feature = "ssm")]
pub mod ssm;
#[cfg(feature = "cloudwatch")]
pub mod cloudwatch;
#[cfg(feature = "cloudwatchlogs")]
pub mod cloudwatch_logs;
#[cfg(feature = "autoscaling")]
pub mod autoscaling;
#[cfg(feature = "elbv2")]
pub mod elbv2;
#[cfg(feature = "rds")]
pub mod rds;
#[cfg(feature = "ecs")]
pub mod ecs;
#[cfg(feature = "kms")]
pub mod kms;
#[cfg(feature = "sqs")]
pub mod sqs;
#[cfg(feature = "sns")]
pub mod sns;
#[cfg(feature = "secretsmanager")]
pub mod secrets_manager;
#[cfg(feature = "route53")]
pub mod route53;
#[cfg(feature = "dynamodb")]
pub mod dynamodb;
#[cfg(feature = "opensearch")]
pub mod opensearch;
#[cfg(feature = "eks")]
pub mod eks;
#[cfg(feature = "acm")]
pub mod acm;
#[cfg(feature = "iam")]
pub mod iam;
#[cfg(feature = "ecr")]
pub mod ecr;
#[cfg(feature = "cloudfront")]
pub mod cloudfront;
#[cfg(feature = "elasticache")]
pub mod elasticache;
#[cfg(feature = "cloudformation")]
pub mod cloudformation;
#[cfg(feature = "eventbridge")]
pub mod eventbridge;
#[cfg(feature = "guardduty")]
pub mod guardduty;
#[cfg(feature = "config")]
pub mod config_svc;
#[cfg(feature = "codepipeline")]
pub mod codepipeline;
#[cfg(feature = "codebuild")]
pub mod codebuild;
#[cfg(feature = "codedeploy")]
pub mod codedeploy;
#[cfg(feature = "kinesis")]
pub mod kinesis;
#[cfg(feature = "firehose")]
pub mod firehose;
#[cfg(feature = "kafka")]
pub mod msk;
#[cfg(feature = "redshift")]
pub mod redshift;
#[cfg(feature = "redshiftserverless")]
pub mod redshift_serverless;
#[cfg(feature = "memorydb")]
pub mod memorydb;
#[cfg(feature = "sfn")]
pub mod step_functions;
#[cfg(feature = "costexplorer")]
pub mod cost_explorer;
#[cfg(feature = "sts")]
pub mod sts;
#[cfg(feature = "cloudtrail")]
pub mod cloudtrail;
#[cfg(feature = "wafv2")]
pub mod wafv2;
#[cfg(feature = "glue")]
pub mod glue;
#[cfg(feature = "efs")]
pub mod efs;
#[cfg(feature = "athena")]
pub mod athena;
#[cfg(feature = "organizations")]
pub mod organizations;
#[cfg(feature = "cognitoidentityprovider")]
pub mod cognito;
#[cfg(feature = "appsync")]
pub mod appsync;
#[cfg(feature = "backup")]
pub mod backup;
#[cfg(feature = "servicequotas")]
pub mod service_quotas;
#[cfg(feature = "health")]
pub mod health;
#[cfg(feature = "inspector2")]
pub mod inspector;
#[cfg(feature = "securityhub")]
pub mod security_hub;
#[cfg(feature = "neptune")]
pub mod neptune;
#[cfg(feature = "docdb")]
pub mod documentdb;
#[cfg(feature = "emr")]
pub mod emr;
#[cfg(feature = "sagemaker")]
pub mod sagemaker;
#[cfg(feature = "batch")]
pub mod batch;
#[cfg(feature = "transfer")]
pub mod transfer;
#[cfg(feature = "appconfig")]
pub mod appconfig;
#[cfg(feature = "globalaccelerator")]
pub mod global_accelerator;
#[cfg(feature = "directconnect")]
pub mod direct_connect;
#[cfg(feature = "macie2")]
pub mod macie;
#[cfg(feature = "networkfirewall")]
pub mod network_firewall;
#[cfg(feature = "shield")]
pub mod shield;
#[cfg(feature = "apigateway")]
pub mod apigateway;
#[cfg(feature = "apigatewayv2")]
pub mod apigatewayv2;
#[cfg(feature = "ssoadmin")]
pub mod sso_admin;
#[cfg(feature = "acmpca")]
pub mod acm_pca;
#[cfg(feature = "ram")]
pub mod ram;
#[cfg(feature = "controltower")]
pub mod control_tower;
#[cfg(feature = "fms")]
pub mod fms;
#[cfg(feature = "auditmanager")]
pub mod audit_manager;
#[cfg(feature = "detective")]
pub mod detective;

#[cfg(feature = "sesv2")]
pub mod ses;

#[cfg(feature = "elasticbeanstalk")]
pub mod elastic_beanstalk;

#[cfg(feature = "apprunner")]
pub mod app_runner;

#[cfg(feature = "fsx")]
pub mod fsx;
#[cfg(feature = "mq")]
pub mod mq;
#[cfg(feature = "dms")]
pub mod dms;
#[cfg(feature = "workspaces")]
pub mod workspaces;
#[cfg(feature = "storagegateway")]
pub mod storage_gateway;
#[cfg(feature = "datasync")]
pub mod datasync;
#[cfg(feature = "lightsail")]
pub mod lightsail;
#[cfg(feature = "qldb")]
pub mod qldb;
#[cfg(feature = "keyspaces")]
pub mod keyspaces;
#[cfg(feature = "bedrock")]
pub mod bedrock;
#[cfg(feature = "xray")]
pub mod xray;
#[cfg(feature = "timestream")]
pub mod timestream;
#[cfg(feature = "lakeformation")]
pub mod lake_formation;
#[cfg(feature = "quicksight")]
pub mod quicksight;
#[cfg(feature = "comprehend")]
pub mod comprehend;
#[cfg(feature = "rekognition")]
pub mod rekognition;
#[cfg(feature = "transcribe")]
pub mod transcribe;
#[cfg(feature = "translate")]
pub mod translate;
#[cfg(feature = "polly")]
pub mod polly;
#[cfg(feature = "codeartifact")]
pub mod codeartifact;
#[cfg(feature = "codecommit")]
pub mod codecommit;
#[cfg(feature = "iot")]
pub mod iot;
#[cfg(feature = "licensemanager")]
pub mod license_manager;
#[cfg(feature = "budgets")]
pub mod budgets;
#[cfg(feature = "connect")]
pub mod connect;
#[cfg(feature = "pinpoint")]
pub mod pinpoint;
