#!/usr/bin/env bash
set -euo pipefail

# Generate the Kiro steering file from the canonical Claude skill.
#
# `skills/aws-vapor/` is the single source of truth for agent-facing vapor
# documentation. Claude Code consumes it directly (SKILL.md loads on trigger,
# references/ load on demand). Kiro has no equivalent progressive-disclosure
# mechanism and its `#[[file:path]]` includes resolve against the *consuming*
# workspace, not this repo — so a copied steering file with includes would
# dangle. This script therefore flattens the skill into one self-contained
# file that a Kiro user drops into their own `.kiro/steering/`.
#
# Usage:
#   ./scripts/build-kiro-steering.sh
#   # → kiro/steering/vapor.md  (committed, so Kiro users can grab it directly)

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
skill_dir="$repo_root/skills/aws-vapor"
out_dir="$repo_root/kiro/steering"
out="$out_dir/vapor.md"

mkdir -p "$out_dir"

# `inclusion: manual` keeps this out of every prompt — the whole point of vapor
# is spending fewer tokens, so it loads only when the user types #vapor or the
# task is actually about AWS.
cat > "$out" <<'EOF'
---
inclusion: manual
---

<!--
  GENERATED by scripts/build-kiro-steering.sh from skills/aws-vapor/.
  Do not edit here — edit the skill and regenerate.

  Install: copy this file into your workspace as .kiro/steering/vapor.md,
  then reference it in chat with #vapor.
-->

EOF

# Cross-file links become in-document pointers once flattened. The link text is
# usually the path itself, so replacing the whole link (not just its target)
# avoids leaving a stray `references/foo.md` in the prose.
rewrite_links() {
  sed -E 's@\[[^]]+\]\((references/)?([a-z-]+)\.md\)@the "\2" section below@g'
}

# Strip the SKILL.md YAML front matter, which is Claude-specific.
awk 'NR==1 && /^---$/ {infm=1; next} infm && /^---$/ {infm=0; next} !infm' \
  "$skill_dir/SKILL.md" \
  | rewrite_links >> "$out"

for ref in prefixes conventions errors feature-flags examples; do
  printf '\n---\n\n### Section: %s\n\n' "$ref" >> "$out"
  rewrite_links < "$skill_dir/references/$ref.md" >> "$out"
done

echo "wrote $out ($(wc -l < "$out") lines)"
