//! The AWS services compiled into this binary.
//!
//! `ENABLED_SERVICES` is generated by `build.rs` from the feature set cargo was
//! invoked with, so it always describes the binary actually running rather than
//! the full catalogue in `Cargo.toml`.

include!(concat!(env!("OUT_DIR"), "/enabled_services.rs"));
