name: CD - Continuous Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    # Build for Linux
    - name: Build Linux release
      run: |
        cargo build --release --target x86_64-unknown-linux-gnu
        tar -czf vapor-linux.tar.gz -C target/x86_64-unknown-linux-gnu/release vapor

    # Build for macOS
    - name: Build macOS release
      run: |
        cargo build --release --target x86_64-apple-darwin
        tar -czf vapor-macos.tar.gz -C target/x86_64-apple-darwin/release vapor

    # Build for Windows
    - name: Build Windows release
      run: |
        cargo build --release --target x86_64-pc-windows-gnu
        7z a vapor-windows.zip target/x86_64-pc-windows-gnu/release/vapor.exe

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          vapor-linux.tar.gz
          vapor-macos.tar.gz
          vapor-windows.zip